### ISSUE TITLE
Email setup local development

### ISSUE THREAD

**Issue by pekrau** [pekrau/DataGraphics#149]
For local development, use my Gmail account thus:

```
mail_settings = {
    "MAIL_SERVER": 'smtp.gmail.com',
    "MAIL_PORT": 465,
    "MAIL_USE_TLS": False,
    "MAIL_USE_SSL": True,
    "MAIL_USERNAME": 'YOUR_GMAIL',
    "MAIL_PASSWORD": 'YOUR_PASSWORD'
}
```

Se https://medium.com/analytics-vidhya/send-email-with-gmail-python-and-flask-1810c25cf5f5

**Comment by rexdivakar** [comment]
Do u wanna add in email setup ?

**Comment by pekrau** [comment]
This issue is basically just a reminder to myself. The email code is already there.

**Comment by pekrau** [comment]
Done
