### ISSUE TITLE
Not possible to update a datafile with columns in addition to the original columns

### ISSUE THREAD

**Issue by akochari** [pekrau/DataGraphics#224]
It would be good to be able to upload a datafile with additional columns (i.e., in addition to the columns that already were present in the initially uploaded datafile). This is at the moment impossible. When I try to add a .CSV file with new columns to an existing dataset, I get an Internal Server Error.

**Comment by pekrau** [comment]
I think the appropriate behaviour should be that the extraneous columns are ignored. To add them seems not right. What do you think?
